name: HorseEnhancer
main: com.nevakanezah.horseenhancer.HorseEnhancerPlugin
version: 0.0.2a
api-version: 1.12.2
commands:
  horseenhancer:
    description: Reload the plugin without restarting the server.
    usage: /<command> reload
    aliases: [he]
